language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install numpy networkx coverage python-coveralls
script:
  - export TEST_FLAG='True'
  - nosetests paths_graph -v
        --with-coverage --cover-inclusive --cover-package=paths_graph
        --with-doctest
after_success:
  - coveralls
