language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install numpy networkx=1.11
script:
  - export TEST_FLAG='True'
  - nosetests paths_graph -v -a $NOSEATTR
        --with-coverage --cover-inclusive --cover-package=paths_graph
        --with-doctest --with-doctest-ignore-unicode
after_success:
  - coveralls
